# Generated by Django 6.0.1 on 2026-01-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='mood_type',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('angry', 'Angry'), ('calm', 'Calm'), ('tired', 'Tired')], default='calm', max_length=20),
            preserve_default=False,
        ),
    ]
